#!/usr/bin/env bash
#
# Run all dotfiles cleaners.

set -e

cd "$(dirname $0)"/..

# find the cleaners and run them iteratively
find . -name clean.sh | while read cleaners ; do sh -c "${cleaners}" ; done
